### ISSUE TITLE
Off by one hour?

### ISSUE THREAD

**Issue by spekulatius** [AustinMoninger/twitter-free-mornings#3]
Hey @AustinMoninger 

could it be that my time is off by an hour?

![image](https://user-images.githubusercontent.com/8433587/93705340-7730ac00-fb2d-11ea-9df1-54e880640886.png)

Cheers!

**Comment by AustinMoninger** [comment]
Hey @spekulatius , what's the issue here? It looks like it's 10:38, meaning it's between 21 and 22 minutes until 11AM.

**Comment by spekulatius** [comment]
Oh, I somehow expected 12 as the limit, isn't it?

**Comment by AustinMoninger** [comment]
It was noted that 11AM is the cutoff on the PH and Chrome store pages. It was fairly arbitrary, but having noon as the cutoff is probably truer to the name (and will save me another hour 😉 ).

I went ahead and pushed a fix, sent out the package for review, and update the descriptions everywhere! Thanks again 😊

**Comment by spekulatius** [comment]
hahahaha, okay. The 11am part skipped my mind totally. I somehow totally expect it to be 12 :D I'll push an update to Mozilla 🦊️

**Comment by spekulatius** [comment]
Done, it's approved!
